In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('IRIS.csv')
df = pd.DataFrame(data)
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
import pandas as pd
import pycaret
from pycaret.classification import *

# Load the CSV data into a pandas DataFrame first
df_pycaret = pd.read_csv('IRIS.csv')

# 2. Setup the PyCaret environment
# PyCaret handles missing values, encoding, and scaling automatically.
# We pass your original unsplit dataframe 'df_pycaret' and define 'charges' as the target.
flower_classification = setup(
    data=df_pycaret,
    target='species',
)

In [7]:
model = compare_models()

In [8]:
x = df.drop('species', axis = 1)
y = df['species']
display(x)
display(y)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [9]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 1. Load and split data
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2, random_state = 42
)

# Check the split
print("x_train:", X_train.shape)
print("x_test: ", X_test.shape)
print("y_train:", y_train.shape)
print("y_test: ", y_test.shape)

# 2. Initialize and fit the QDA model
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)

# 3. Make predictions and evaluate
y_pred = qda.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

x_train: (120, 4)
x_test:  (30, 4)
y_train: (120,)
y_test:  (30,)
Accuracy: 0.9666666666666667

In [10]:
# 1. Enter custom flower measurements
custom_data = pd.DataFrame({
    'sepal_length': [5.1],
    'sepal_width': [3.5],
    'petal_length': [1.4],
    'petal_width': [0.2]
})

# 2. Predict the flower species
prediction = qda.predict(custom_data)

# 3. Display the result
print("Custom Input:")
print(custom_data)

print("\nPredicted Species:", prediction[0])

# 4. Display prediction probabilities
probabilities = qda.predict_proba(custom_data)

probability_df = pd.DataFrame(
    probabilities,
    columns=qda.classes_
)

print("\nPrediction Probabilities:")
print(probability_df.round(4))

Custom Input:
   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

Predicted Species: Iris-setosa

Prediction Probabilities:
   Iris-setosa  Iris-versicolor  Iris-virginica
0          1.0              0.0             0.0

In [13]:
import joblib

# Bundle everything into a single dictionary
bundle = {
    'model': qda,
    'features': list(df.columns)
}

# Save into a single pickle file
joblib.dump(bundle, 'iris.pkl')
print("Successfully saved model, and features to 'iris.pkl'!")

Successfully saved model, and features to 'iris.pkl'!